# Generated by Django 6.0.5 on 2026-08-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_randomize_private_evidence_paths'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='manualpayment',
            new_name='payments_ma_status_0321a0_idx',
            old_name='payments_ma_status_37aff2_idx',
        ),
    ]
