# Generated by Django 6.0.5 on 2026-06-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_ne', models.CharField(max_length=255, verbose_name='Name (Nepali)')),
                ('objective_en', models.TextField(verbose_name='Objective (English)')),
                ('objective_ne', models.TextField(verbose_name='Objective (Nepali)')),
                ('slogan_en', models.TextField(verbose_name='Slogan (English)')),
                ('slogan_ne', models.TextField(verbose_name='Slogan (Nepali)')),
                ('commitment_en', models.TextField(verbose_name='Commitment (English)')),
                ('commitment_ne', models.TextField(verbose_name='Commitment (Nepali)')),
            ],
        ),
    ]
