# Generated by Django 6.0.5 on 2026-06-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ne', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(default='🌐', max_length=10)),
                ('min_wage_ne', models.CharField(default='रु ४५,०००', max_length=100)),
                ('min_wage_en', models.CharField(default='NPR 45,000 equivalent', max_length=100)),
                ('laws_summary_ne', models.TextField()),
                ('laws_summary_en', models.TextField()),
                ('embassy_contact_ne', models.TextField()),
                ('embassy_contact_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('file_size', models.CharField(default='2.4 MB', max_length=50)),
                ('download_url', models.CharField(default='#', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_svg', models.TextField(help_text='Paste raw HTML/SVG icon code here.', verbose_name='Raw SVG Icon Code')),
                ('title_ne', models.CharField(max_length=255, verbose_name='Title (Nepali)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('desc_ne', models.TextField(verbose_name='Description (Nepali)')),
                ('desc_en', models.TextField(verbose_name='Description (English)')),
                ('process_ne', models.TextField(default='सम्बन्धित कागजात सहित केन्द्रमा सम्पर्क राख्ने।', verbose_name='Process Steps (Nepali)')),
                ('process_en', models.TextField(default='Contact the center with all necessary documentation.', verbose_name='Process Steps (English)')),
            ],
        ),
        migrations.AlterModelOptions(
            name='organizationinfo',
            options={'verbose_name': 'Organization Information', 'verbose_name_plural': 'Organization Information'},
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='chairperson_message_en',
            field=models.TextField(default='Safe and dignified foreign employment is our primary mission.'),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='chairperson_message_ne',
            field=models.TextField(default='सुरक्षित र मर्यादित वैदेशिक रोजगारी नै हाम्रो मुख्य लक्ष्य हो।'),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='chairperson_name_en',
            field=models.CharField(default='Ram Bahadur Gurung', max_length=255),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='chairperson_name_ne',
            field=models.CharField(default='राम बहादुर गुरुङ', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationinfo',
            name='slogan_en',
            field=models.CharField(max_length=500, verbose_name='Slogan (English)'),
        ),
        migrations.AlterField(
            model_name='organizationinfo',
            name='slogan_ne',
            field=models.CharField(max_length=500, verbose_name='Slogan (Nepali)'),
        ),
    ]
