# Generated by Django 6.0.5 on 2026-06-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_destinationcountry_resourcepublication_servicecard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('designation', models.CharField(max_length=100, verbose_name='Official Designation')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Official Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Extension / Phone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_photos/', verbose_name='Profile Photo')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers display first.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on Website')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
