# Generated by Django 6.0.5 on 2026-06-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_membership_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('life', 'Life Member'), ('general', 'General Member')], max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='municipality',
            field=models.CharField(choices=[('ilam', 'Ilam Municipality'), ('deumai', 'Deumai Municipality'), ('suryodaya', 'Suryodaya Municipality'), ('phakphokthum', 'Phakphokthum Rural Municipality'), ('sandakpur', 'Sandakpur Rural Municipality')], max_length=50),
        ),
    ]
