# Generated by Django 6.0.5 on 2026-07-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_model_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='membership',
            name='designation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='membership',
            name='destination_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membership',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membership',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='ward_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
