# Generated by Django 6.0.5 on 2026-07-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_membership_address_membership_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinfo',
            name='chairperson_photo',
            field=models.ImageField(blank=True, null=True, upload_to='chairperson_photos/', verbose_name='Chairperson Photo'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
    ]
