# Generated by Django 6.0.5 on 2026-08-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_counseling_first_content'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='officialresource',
            new_name='core_offici_is_acti_46af23_idx',
            old_name='core_offici_is_acti_fcd077_idx',
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='process_en',
            field=models.TextField(blank=True, verbose_name='Process Steps (English)'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='process_ne',
            field=models.TextField(blank=True, verbose_name='Process Steps (Nepali)'),
        ),
    ]
