# Generated by Django 6.0.5 on 2026-06-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_homepage_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='blog_articl_is_aler_5de6f5_idx',
            old_name='blog_articl_is_aler_idx',
        ),
    ]
