# Generated by Django 6.0.5 on 2026-06-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('municipality', models.CharField(choices=[('ilam', 'इलाम नगरपालिका'), ('deumai', 'देउमाइ नगरपालिका'), ('suryodaya', 'सुर्योदय नगरपालिका'), ('phakphokthum', 'फाकफोकथुम गाउपालिका'), ('sandakpur', 'सन्दकपुर गाउपालिका')], max_length=50)),
                ('membership_type', models.CharField(choices=[('life', 'आजिबन सदस्य'), ('general', 'साधारण सदस्य')], max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
