# Generated by Django 6.0.5 on 2026-06-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
