from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):
    dependencies = [("core", "0012_membership_email")]

    operations = [
        migrations.AddField(model_name="organizationinfo", name="registration_number", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="organizationinfo", name="established_date", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="organizationinfo", name="official_phone", field=models.CharField(blank=True, max_length=30)),
        migrations.AddField(model_name="organizationinfo", name="official_email", field=models.EmailField(blank=True, max_length=254)),
        migrations.AddField(model_name="organizationinfo", name="office_address_ne", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="organizationinfo", name="office_address_en", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="organizationinfo", name="service_hours_ne", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="organizationinfo", name="service_hours_en", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="organizationinfo", name="disclaimer_ne", field=models.TextField(default="हामी वैदेशिक रोजगारसम्बन्धी सूचना, सचेतना र परामर्श प्रदान गर्छौं। हामी भिसा जारी गर्दैनौं, रोजगारीको ग्यारेन्टी गर्दैनौं र भर्ती एजेन्सी होइनौं।")),
        migrations.AddField(model_name="organizationinfo", name="disclaimer_en", field=models.TextField(default="We provide information, awareness, and counseling related to foreign employment. We do not issue visas, guarantee employment, or operate as a recruitment agency.")),
        migrations.AlterField(model_name="organizationinfo", name="chairperson_name_ne", field=models.CharField(default="[CHAIRPERSON NAME]", max_length=255)),
        migrations.AlterField(model_name="organizationinfo", name="chairperson_name_en", field=models.CharField(default="[CHAIRPERSON NAME]", max_length=255)),
        migrations.AlterField(model_name="organizationinfo", name="chairperson_message_ne", field=models.TextField(default="[CHAIRPERSON MESSAGE IN NEPALI]")),
        migrations.AlterField(model_name="organizationinfo", name="chairperson_message_en", field=models.TextField(default="[CHAIRPERSON MESSAGE IN ENGLISH]")),
        migrations.AddField(model_name="servicecard", name="icon_name", field=models.CharField(choices=[("guidance", "Guidance"), ("shield", "Safety"), ("document", "Documents"), ("rights", "Rights"), ("family", "Family"), ("return", "Return")], default="guidance", max_length=30)),
        migrations.AddField(model_name="servicecard", name="display_order", field=models.PositiveSmallIntegerField(default=0)),
        migrations.AddField(model_name="servicecard", name="is_active", field=models.BooleanField(default=True)),
        migrations.AlterField(model_name="servicecard", name="icon_svg", field=models.TextField(blank=True, help_text="Legacy field. Raw SVG is no longer rendered publicly.", verbose_name="Legacy raw SVG")),
        migrations.AlterModelOptions(name="servicecard", options={"ordering": ["display_order", "id"]}),
        migrations.AddField(model_name="destinationcountry", name="last_reviewed", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="destinationcountry", name="is_active", field=models.BooleanField(default=True)),
        migrations.AlterField(model_name="destinationcountry", name="estimated_cost", field=models.PositiveIntegerField(default=0, help_text="Informational estimate only. Set to zero when unverified.")),
        migrations.AlterField(model_name="servicecard", name="process_ne", field=models.TextField(blank=True, verbose_name="Process Steps (Nepali)")),
        migrations.AlterField(model_name="servicecard", name="process_en", field=models.TextField(blank=True, verbose_name="Process Steps (English)")),
        migrations.AlterField(model_name="destinationcountry", name="min_wage_ne", field=models.CharField(blank=True, max_length=100)),
        migrations.AlterField(model_name="destinationcountry", name="min_wage_en", field=models.CharField(blank=True, max_length=100)),
        migrations.AlterField(model_name="destinationcountry", name="laws_summary_ne", field=models.TextField(blank=True)),
        migrations.AlterField(model_name="destinationcountry", name="laws_summary_en", field=models.TextField(blank=True)),
        migrations.AlterField(model_name="destinationcountry", name="embassy_contact_ne", field=models.TextField(blank=True)),
        migrations.AlterField(model_name="destinationcountry", name="embassy_contact_en", field=models.TextField(blank=True)),
        migrations.AlterField(model_name="resourcepublication", name="file_size", field=models.CharField(blank=True, max_length=50)),
        migrations.AlterField(model_name="resourcepublication", name="download_url", field=models.CharField(blank=True, max_length=500)),
        migrations.AlterModelOptions(name="resourcepublication", options={"ordering": ["-id"], "verbose_name": "Legacy resource publication"}),
        migrations.AddField(model_name="contactmessage", name="phone", field=models.CharField(default="", max_length=24), preserve_default=False),
        migrations.AddField(model_name="contactmessage", name="preferred_language", field=models.CharField(choices=[("ne", "Nepali"), ("en", "English"), ("either", "Either")], default="ne", max_length=10)),
        migrations.AddField(model_name="contactmessage", name="consent_to_contact", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="contactmessage", name="status", field=models.CharField(choices=[("new", "New"), ("reviewed", "Reviewed"), ("closed", "Closed"), ("spam", "Spam")], default="new", max_length=20)),
        migrations.AlterField(model_name="contactmessage", name="email", field=models.EmailField(blank=True, max_length=254)),
        migrations.AlterField(model_name="contactmessage", name="message", field=models.TextField(max_length=5000)),
        migrations.AlterField(model_name="membership", name="phone", field=models.CharField(max_length=20)),
        migrations.AlterModelOptions(name="membership", options={"ordering": ["-joined_date"], "verbose_name": "Membership application", "verbose_name_plural": "Membership applications"}),
        migrations.CreateModel(
            name="EmergencyResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title_ne", models.CharField(max_length=180)),
                ("title_en", models.CharField(max_length=180)),
                ("guidance_ne", models.TextField(blank=True)),
                ("guidance_en", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("url", models.URLField(blank=True, max_length=600)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("last_reviewed", models.DateField(blank=True, null=True)),
            ],
            options={"ordering": ["display_order", "title_en"]},
        ),
        migrations.CreateModel(
            name="FrequentlyAskedQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_ne", models.CharField(max_length=300)),
                ("question_en", models.CharField(max_length=300)),
                ("answer_ne", models.TextField()),
                ("answer_en", models.TextField()),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["display_order", "id"]},
        ),
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name_ne", models.CharField(max_length=150)),
                ("name_en", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["display_order", "name_en"], "verbose_name_plural": "Resource categories"},
        ),
        migrations.CreateModel(
            name="OfficialResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title_ne", models.CharField(blank=True, max_length=255)),
                ("title_en", models.CharField(blank=True, max_length=255)),
                ("description_ne", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("url", models.URLField(max_length=600, validators=[django.core.validators.URLValidator(schemes=["https"])])),
                ("is_official_source", models.BooleanField(default=True)),
                ("language", models.CharField(choices=[("both", "Both languages"), ("ne", "Nepali"), ("en", "English")], default="both", max_length=10)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("last_reviewed", models.DateField(blank=True, null=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="resources", to="core.resourcecategory")),
            ],
            options={"ordering": ["category__display_order", "display_order", "title_en"]},
        ),
        migrations.AddIndex(model_name="officialresource", index=models.Index(fields=["is_active", "category", "display_order"], name="core_offici_is_acti_46af23_idx")),
    ]
