# Generated by Django 6.0.5 on 2026-06-10 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=255, verbose_name='Title (Nepali)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('content_ne', models.TextField(verbose_name='Content (Nepali)')),
                ('content_en', models.TextField(verbose_name='Content (English)')),
                ('featured_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Featured Image URL')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('is_alert', models.BooleanField(default=False, verbose_name='Is Critical Emergency Alert?')),
            ],
            options={
                'verbose_name': 'Articles',
                'ordering': ['-published_date'],
            },
        ),
    ]
