# Generated by Django 6.0.5 on 2026-06-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photos/', verbose_name='Upload Photo from Device'),
        ),
    ]
