# Generated by Django 6.0.5 on 2026-08-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_professional_publishing'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='blog_articl_status_5e4672_idx',
            old_name='blog_articl_status_30f6ef_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='blog_articl_article_bc14eb_idx',
            old_name='blog_articl_article_f0dcbb_idx',
        ),
    ]
