# Generated by Django 6.0.5 on 2026-07-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ne', models.CharField(max_length=150, verbose_name='Name (Nepali)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='Name (English)')),
                ('membership_number', models.CharField(blank=True, max_length=50, verbose_name='Membership Number')),
                ('membership_type', models.CharField(choices=[('life', 'Life Member'), ('general', 'General Member')], default='general', max_length=20, verbose_name='Membership Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Status')),
                ('level', models.CharField(choices=[('district', 'District'), ('municipality', 'Municipality'), ('rural_municipality', 'Rural Municipality'), ('ward', 'Ward'), ('unknown', 'Unknown')], default='unknown', max_length=30, verbose_name='Organization Level')),
                ('municipality', models.CharField(blank=True, max_length=100, verbose_name='Municipality / Rural Municipality')),
                ('ward_no', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ward Number')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('designation', models.CharField(blank=True, max_length=150, verbose_name='Designation / Position')),
                ('destination_country', models.CharField(blank=True, max_length=100, verbose_name='Foreign Employment Country')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('show_phone_publicly', models.BooleanField(default=False, verbose_name='Show Phone Publicly')),
                ('is_public', models.BooleanField(default=True, verbose_name='Show on Website')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers display first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['sort_order', 'name_ne'],
                'indexes': [models.Index(fields=['membership_type'], name='members_mem_members_730b94_idx'), models.Index(fields=['status'], name='members_mem_status_734de0_idx'), models.Index(fields=['municipality'], name='members_mem_municip_23c280_idx'), models.Index(fields=['is_public'], name='members_mem_is_publ_7922c4_idx')],
            },
        ),
    ]
