# Generated by Django 6.0.5 on 2026-07-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_unit_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['level', 'unit_name', 'membership_type', 'membership_number_int', 'sort_order', 'name_ne'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='ward_no',
        ),
        migrations.AddField(
            model_name='member',
            name='membership_number_int',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Membership Number for Sorting'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_number',
            field=models.CharField(blank=True, help_text='Isolated inside Level + Unit + Membership Type. Example: District life no. 4 and Ilam Municipality life no. 1 can both exist.', max_length=50, verbose_name='Membership Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='unit_name',
            field=models.CharField(blank=True, help_text='Example: Ilam District, Ilam Municipality', max_length=150, verbose_name='Committee / Unit Name'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['level'], name='members_mem_level_1e364b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['unit_name'], name='members_mem_unit_na_41fefa_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('membership_number', ''), _negated=True), fields=('level', 'unit_name', 'membership_type', 'membership_number'), name='unique_member_no_per_isolated_member_registry'),
        ),
    ]
