# Generated by Django 6.0.5 on 2026-07-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_options_remove_member_ward_no_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='member',
            name='unique_member_no_per_isolated_member_registry',
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('membership_number_int__isnull', False)), fields=('level', 'unit_name', 'membership_type', 'membership_number_int'), name='unique_member_no_per_isolated_member_registry'),
        ),
    ]
