# Generated by Django 6.0.5 on 2026-08-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_membershiprecord_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['level', 'unit_name', 'membership_type', 'membership_number_int', 'sort_order', 'name_ne'], 'verbose_name': 'Legacy member record', 'verbose_name_plural': 'Legacy member records'},
        ),
        migrations.RenameIndex(
            model_name='importbatch',
            new_name='members_imp_source__3cf2f7_idx',
            old_name='members_imp_source__dcd5f8_idx',
        ),
        migrations.RenameIndex(
            model_name='membershiprecord',
            new_name='members_mem_person__595e95_idx',
            old_name='members_mem_person__7aa822_idx',
        ),
        migrations.RenameIndex(
            model_name='membershiprecord',
            new_name='members_mem_categor_03f66b_idx',
            old_name='members_mem_categor_57ea25_idx',
        ),
        migrations.RenameIndex(
            model_name='membershiprecord',
            new_name='members_mem_organiz_736b64_idx',
            old_name='members_mem_organiz_e4fc75_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='members_per_is_publ_0e9b4d_idx',
            old_name='members_per_is_publ_4f7d57_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='members_per_phone_101b30_idx',
            old_name='members_per_phone_607f3f_idx',
        ),
    ]
