# Generated by Django 6.0.5 on 2026-08-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_randomize_private_attachment_paths'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='counselingrequest',
            new_name='counseling__status_c0a6bb_idx',
            old_name='counseling__status_8a4ba4_idx',
        ),
        migrations.RenameIndex(
            model_name='counselingrequest',
            new_name='counseling__assigne_fd782a_idx',
            old_name='counseling__assigned_85ea5d_idx',
        ),
    ]
