# Generated by Django 6.0.5 on 2026-07-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='unit_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Committee / Unit Name'),
        ),
    ]
